import { ChevronDownIcon, MinusIcon, PlusIcon } from 'lucide-react';
import React, { useState } from 'react'

export default function Faq() {

  const [faq, setFaq] = useState('null') as any;

  const answers = [
    {
      "question": "What is GrowStream?",
      "answer": "🌱 GrowStream is an innovative project where plant growth is streamed live 24/7, symbolizing the development of your investment. Just like a seed takes time to sprout, the value of $GROW grows with the patience of the community."
    },
    {
      "question": "Where is GrowStream launched?",
      "answer": "GrowStream is officially launched on PumpFun, bringing together real-time streaming and token growth in a unique way."
    },
    {
      "question": "How does GrowStream work?",
      "answer": "We combine nature, technology, and finance. As you watch a live plant grow on stream, it represents the steady, organic growth of your investment. Patience and community support drive the project forward."
    },
    {
      "question": "Why is GrowStream unique?",
      "answer": "Unlike typical meme or utility tokens, GrowStream visually connects investors with nature by streaming plant growth live on PumpFun – making growth transparent, relatable, and symbolic."
    },
    {
      "question": "How can I join the GrowStream community?",
      "answer": "You can buy $GROW directly on PumpFun, follow our live growth stream, and engage with the community on Telegram and Twitter to be part of the journey."
    },
    {
      "question": "What happens with the creator fees on PumpFun?",
      "answer": "The creator fees generated by PumpFun will be channeled into supporting green world energy initiatives: Planting trees, renewable energy projects, and eco-friendly campaigns that align with our vision of sustainable growth."
    }
  ];


  return (
    <section id="faq" className="relative py-12 text-black">
      <div className="my-10 max-w-[900px] w-[95%] mx-auto">
        <h1 className='text-4xl md:text-5xl text-center underred comics text-black'>Frequently Asked Questions.</h1>
        <div className='mt-10 border-2 border-black p-2 border-b-8 border-r-8'>
          {
            answers.map((ans, i) => (
              <div key={i} onClick={() => setFaq(faq === i ? null : i)} className={`${i < 3 && 'border-b'} border-opacity-50 border-black mt-4`}>
                <div className="rounded-md p-5 flex items-center justify-between gap-2 cursor-pointer">
                  <h1 className="text-xl md:text-xl comics">{i + 1} {answers[i].question}</h1>
                  <div className='center border-black relative px-2 py-1'>
                    {faq == i ? <MinusIcon className='text-white relative z-20' /> : <PlusIcon className='text-white relative z-20' />}
                    <div className='bg-black h-full -bottom-1 -right-1 w-full absolute' />
                    <div className='bg-blue h-full top-0 w-full absolute' />
                  </div>
                </div>
                {(faq === i) && <p className="p-5 comic">{answers[i].answer}</p>}
              </div>
            ))
          }
        </div>
      </div>
    </section>
  )
}